name: Claude Jira Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
jobs:
  claude-jira-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Jira Review
        id: claude-jira-review
        uses: anthropics/claude-code-action@v1
        env:
          CLAUDE_CODE_DISABLE_BACKGROUND_TASKS: "1"
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        with:
          show_full_output: true
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            PR Number: ${{ github.event.pull_request.number }}
            Take Jira ticket number from the PR title, it looks following way <KAN-XXXX>
            use mcp__mcp-atlassian__jira_get_issue tool to get the Jira ticket details.
            then get code changes made on this PR. Review them compared to Jira implementation ticket.
            Write me a summary of what is missing it implement and what code was added that is not relates to Jira ticket and put a comment in PR.
            use jira-report-template.md as a comment template
          claude_args: '--allowedTools "mcp__mcp-atlassian__jira_get_issue,Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr comment:*)"'
